### ISSUE TITLE
Katowice - Brynow Track 1 has no singals defined

### ISSUE THREAD

**Issue by The-Luz** [besentv/besentv.github.io#10]
![image](https://github.com/user-attachments/assets/672b1100-0531-4c96-9565-3ae03826969c)

Segments 15 and 20 have no defined Signals
Should be:

20:
<-  l139_bry_a 
-> l139_20 

15:
  <- l139_15
 ->  KO_T

**Comment by besentv** [comment]
Fixed with 53670872085cf9ba19a26ff5fe5d332c333fe452
